In [52]:
import pandas as pd
naukri_df=pd.read_csv("source1_naukri_applicants.csv")

In [7]:
naukri_df

,Full Name,Email,Phone,City,Experience (Years),Current CTC,Applied Date,Skills
0,Tanvi Gupta,tanvi.gupta31@example.com,919000000254,Bengaluru,4.2,417964.0,24-07-2026,"n8n, LangChain, REST APIs, MongoDB, SQL"
1,Manish Reddy,manish.reddy73@example.com,9000000237,GURGAON,3.5,332456.0,2026-08-08,"Docker, Zapier, JavaScript"
2,Priya Singh,priya.singh61@mailtest.example.org,9000000287,GURGAON,3.0,775670.0,01-08-2026,"React, Zapier, n8n, MySQL, Python, SQL"
3,Vikram Saxena,vikram.saxena60@example.com,9000000113,GURGAON,1.9,654699.0,7 Jul 2026,"Selenium, Web Scraping, React, Docker, SQL, Fa..."
4,Amit Agarwal,amit.agarwal3@mailtest.example.org,919000000288,pune,1.8,4.2,19-07-2026,"SQL, Python, JavaScript, Docker"
5,Sahil Malhotra,sahil.malhotra1@example.in,919000000143,Noida,1.7,806661.0,07/13/2026,"FastAPI, Docker, MySQL, Zapier, Pandas, REST APIs"
6,Shreya Gupta,shreya.gupta85@example.com,9000000227,NOIDA,3.3,8.3,19 Jul 2026,"Zapier, Web Scraping, Docker, n8n, Python"
7,Isha Chopra,isha.chopra95@mailtest.example.org,9000000138,PUNE,5.4,472935.0,2026-08-02,"React, JavaScript, MySQL"
8,Priya Nair,priya.nair70@example.com,919000000222,gurugram,5.6,366311.0,28-07-2026,"Zapier, REST APIs, React, Python, n8n, Web Scr..."
9,Rohit Mishra,rohit.mishra70@mailtest.example.org,9000000167,Delhi,4.4,871686.0,2026-07-13,"Docker, Pandas, FastAPI, SQL, Zapier, MySQL"
10,Rahul Malhotra,rahul.malhotra69@mailtest.example.org,9000000260,new delhi,2.5,864237.0,07/03/2026,"MySQL, REST APIs, SQL, MongoDB, Selenium"
11,Rahul Jain,rahul.jain34@example.in,9000000114,Noida,2.8,1195422.0,2026-06-24,"Zapier, Selenium, Docker, Python"
12,Nikhil Malhotra,nikhil.malhotra41@example.in,9000000145,New Delhi,4.2,5.1,21-08-2026,"FastAPI, JavaScript, Web Scraping, SQL, Python"
13,Karan Bhatia,karan.bhatia32@mailtest.example.org,919000000211,Noida,4.7,826748.0,8 Jul 2026,"SQL, MongoDB, Selenium, Zapier, Web Scraping, ..."
14,Ritu Sharma,ritu.sharma23@mailtest.example.org,9000000146,Noida,4.8,6.1,2026-08-03,"n8n, Web Scraping, MongoDB, SQL, React"
15,Arjun Mishra,arjun.mishra70@example.com,9000000106,Delhi,1.3,5.8,22-08-2026,"React, Docker, JavaScript"
16,Meera Bhatia,meera.bhatia52@mailtest.example.org,9000000223,Delhi NCR,5.1,11.2,2026-07-03,"LangChain, Docker, MySQL, Python, SQL, React"
17,Varun Jain,varun.jain29@example.com,9000000263,Pune,3.1,7.6,08/19/2026,"n8n, Web Scraping, FastAPI, MySQL, Pandas, Mon..."
18,Arjun Mehta,arjun.mehta9@example.in,9000000131,NOIDA,4.0,1181149.0,21-07-2026,"SQL, Selenium, n8n"
19,Kavya Mehta,kavya.mehta7@example.com,919000000177,Bengaluru,5.1,2.4,2 Jul 2026,"n8n, MongoDB, FastAPI, Pandas, React"
20,Sneha Chopra,sneha.chopra99@example.in,919000000162,pune,4.9,10.0,03-07-2026,"Pandas, React, MySQL, JavaScript, SQL"
21,Deepak Mehta,deepak.mehta86@example.in,9000000116,NOIDA,2.7,327287.0,2026-07-23,"MySQL, MongoDB, n8n, LangChain, REST APIs, Sel..."
22,Pooja Gupta,pooja.gupta57@mailtest.example.org,9000000271,Noida,3.9,11.9,24-06-2026,"Docker, MySQL, SQL, n8n, Selenium"
23,R. Verma,rohit.verma13@mailtest.example.org,9000000294,Bangalore,2.4,6.1,08/13/2026,"Python, React, MongoDB"
24,Sneha Mishra,sneha.mishra14@mailtest.example.org,9000000229,pune,1.4,410629.0,15-06-2026,"MySQL, Docker, Selenium, Pandas"
25,Nikhil Chopra,alt.nikhil.chopra70@example.com,9000000103,NOIDA,0.8,7.8,07/03/2026,"Pandas, SQL, n8n"
26,Priya Saxena,priya.saxena61@example.com,919000000231,Delhi,5.0,6.6,08/16/2026,"Python, MySQL, Zapier, React"
27,Varun Saxena,varun.saxena21@example.in,9000000170,gurugram,3.7,775796.0,5 Jul 2026,"MongoDB, Zapier, SQL, LangChain, MySQL, REST APIs"
28,Gaurav Mehta,gaurav.mehta79@mailtest.example.org,9000000133,Bengaluru,3.1,792474.0,19-07-2026,"REST APIs, SQL, Selenium, FastAPI"
29,Rohit Verma,rohit.verma13@mailtest.example.org,9000000294,Bangalore,2.4,6.1,08/13/2026,"Python, React, MongoDB"
30,Rohit Nair,rohit.nair32@mailtest.example.org,919000000268,Gurugram,2.4,7.6,2026-08-19,"REST APIs, n8n, Web Scraping, Docker"
31,Deepak Nair,deepak.nair44@example.com,9000000296,bangalore,5.0,1160787.0,15 Jul 2026,"React, n8n, MongoDB, Pandas"
32,Rahul Chopra,rahul.chopra70@example.com,9000000137,NOIDA,1.7,2.7,27 Jul 2026,"Zapier, Docker, Python"
33,Deepak Singh,deepak.singh36@mailtest.example.org,9000000202,bangalore,1.7,1135514.0,08/11/2026,"Web Scraping, FastAPI, Docker, React"
34,Amit Reddy,amit.reddy9@mailtest.example.org,9000000165,Delhi NCR,2.7,11.4,21 Jul 2026,"React, MySQL, LangChain"
35,Nikhil Chopra,nikhil.chopra70@example.com,9000000103,NOIDA,0.8,7.8,07/03/2026,"Pandas, SQL, n8n"
36,Tanvi Agarwal,tanvi.agarwal97@example.in,919000000148,PUNE,5.0,626740.0,27 Jul 2026,"MongoDB, REST APIs, FastAPI, Web Scraping"
37,Nikhil Mehta,nikhil.mehta5@example.com,9000000104,PUNE,2.9,9.3,2026-07-26,"Docker, LangChain, Zapier, Selenium, Python, R..."
38,Isha Kapoor,isha.kapoor54@example.com,919000000295,new delhi,5.1,5.9,08/21/2026,"FastAPI, Python, JavaScript, Selenium, React, ..."
39,Arjun Bhatia,arjun.bhatia14@example.com,9000000212,new delhi,1.5,621881.0,02-06-2026,"Zapier, REST APIs, SQL, FastAPI, Pandas, Web S..."
40,Isha Sharma,isha.sharma15@example.com,919000000259,Delhi,3.5,10.3,07/12/2026,"n8n, Python, Selenium, JavaScript, REST APIs, ..."
41,Neha Bhatia,neha.bhatia60@mailtest.example.org,9000000273,Pune,4.2,694306.0,22 Jul 2026,"FastAPI, Zapier, JavaScript, Selenium"

In [69]:
gig_workers_df=pd.read_csv("source2_gig_workers.csv")
gig_workers_df.isnull().sum()

email_id       1
worker_name    1
rate           1
location       1
status         1
skill_tags     1
dtype: int64

In [16]:
gig_workers_df=gig_workers_df.dropna()
gig_workers_df.isnull().sum()

email_id       0
worker_name    0
rate           0
location       0
status         0
skill_tags     0
dtype: int64

In [33]:
cbnexus_contacts_df=pd.read_csv("source3_cbnexus_contacts.csv")
cbnexus_contacts_df

              Name    Phone Number       City  Verified  Projects Completed
0       Rohit Nair      9000000268    Gurgaon         Y                  13
1      RITU SHARMA      9000000146     Noida        yes                  15
2     Priya Saxena    919000000231  New Delhi        No                  12
3      Arjun Mehta  +91-9000000131      Noida        No                   9
4     Nikhil Mehta  +91-9000000104       pune         Y                  10
5   RAHUL MALHOTRA    919000000260  Delhi NCR        No                   4
6     Deepak Mehta      9000000116      Noida       yes                  11
7   SAHIL MALHOTRA      9000000143      Noida         N                   0
8     Shreya Gupta  +91-9000000227      NOIDA       yes                  13
9      Priya Singh      9000000287  gurugram          Y                   3
10      Varun Jain    919000000263       Pune       yes                  14
11   Tanvi Agarwal    919000000148       Pune         N                   3
12    KARAN BHATIA      9000000211      NOIDA       yes                   2
13    Arjun Mishra    919000000106  new delhi        No                  10
14            Name    Phone Number       City  Verified  Projects Completed
15     Isha Kapoor  +91-9000000295  New Delhi       yes                   6
16     Isha Chopra    919000000138       pune        No                   7
17    MEERA BHATIA    919000000223      Delhi        No                   4
18   Vikram Saxena      9000000113    Gurgaon        No                  15
19    Rahul Chopra      9000000137     Noida          N                  10
20     Tanvi Gupta      9000000254  Bengaluru        No                  14
21    VARUN SAXENA    919000000170    GURGAON         Y                   1
22    Sneha Chopra  +91-9000000162       pune         N                  14
23     DEEPAK NAIR    919000000296  Bengaluru       Yes                   2
24    Gaurav Mehta      9000000133  Bengaluru         N                   1
25     Neha Bhatia      9000000273       PUNE        No                  10
26     Arjun Mehta      9000000272      Noida       Yes                  14
27   MANISH BHATIA    919000000161     Noida        Yes                   5
28    DIVYA CHOPRA      9000000111      NOIDA         N                   5
29    Karan Chopra    919000000245       pune         N                  10
30    Vikram Mehta  +91-9000000261       PUNE         Y                   2

In [23]:
cbnexus_contacts_df["City"]=cbnexus_contacts_df["City"].str.capitalize()
cbnexus_contacts_df

              Name    Phone Number       City  Verified  Projects Completed
0       Rohit Nair      9000000268    Gurgaon         Y                  13
1      RITU SHARMA      9000000146     Noida        yes                  15
2     Priya Saxena    919000000231  New delhi        No                  12
3      Arjun Mehta  +91-9000000131      Noida        No                   9
4     Nikhil Mehta  +91-9000000104       Pune         Y                  10
5   RAHUL MALHOTRA    919000000260  Delhi ncr        No                   4
6     Deepak Mehta      9000000116      Noida       yes                  11
7   SAHIL MALHOTRA      9000000143      Noida         N                   0
8     Shreya Gupta  +91-9000000227      Noida       yes                  13
9      Priya Singh      9000000287  Gurugram          Y                   3
10      Varun Jain    919000000263       Pune       yes                  14
11   Tanvi Agarwal    919000000148       Pune         N                   3
12    KARAN BHATIA      9000000211      Noida       yes                   2
13    Arjun Mishra    919000000106  New delhi        No                  10
14            Name    Phone Number       City  Verified  Projects Completed
15     Isha Kapoor  +91-9000000295  New delhi       yes                   6
16     Isha Chopra    919000000138       Pune        No                   7
17    MEERA BHATIA    919000000223      Delhi        No                   4
18   Vikram Saxena      9000000113    Gurgaon        No                  15
19    Rahul Chopra      9000000137     Noida          N                  10
20     Tanvi Gupta      9000000254  Bengaluru        No                  14
21    VARUN SAXENA    919000000170    Gurgaon         Y                   1
22    Sneha Chopra  +91-9000000162       Pune         N                  14
23     DEEPAK NAIR    919000000296  Bengaluru       Yes                   2
24    Gaurav Mehta      9000000133  Bengaluru         N                   1
25     Neha Bhatia      9000000273       Pune        No                  10
26     Arjun Mehta      9000000272      Noida       Yes                  14
27   MANISH BHATIA    919000000161     Noida        Yes                   5
28    DIVYA CHOPRA      9000000111      Noida         N                   5
29    Karan Chopra    919000000245       Pune         N                  10
30    Vikram Mehta  +91-9000000261       Pune         Y                   2

In [34]:
cbnexus_contacts_df = cbnexus_contacts_df.drop(cbnexus_contacts_df.index[14])
cbnexus_contacts_df

              Name    Phone Number       City Verified Projects Completed
0       Rohit Nair      9000000268    Gurgaon        Y                 13
1      RITU SHARMA      9000000146     Noida       yes                 15
2     Priya Saxena    919000000231  New Delhi       No                 12
3      Arjun Mehta  +91-9000000131      Noida       No                  9
4     Nikhil Mehta  +91-9000000104       pune        Y                 10
5   RAHUL MALHOTRA    919000000260  Delhi NCR       No                  4
6     Deepak Mehta      9000000116      Noida      yes                 11
7   SAHIL MALHOTRA      9000000143      Noida        N                  0
8     Shreya Gupta  +91-9000000227      NOIDA      yes                 13
9      Priya Singh      9000000287  gurugram         Y                  3
10      Varun Jain    919000000263       Pune      yes                 14
11   Tanvi Agarwal    919000000148       Pune        N                  3
12    KARAN BHATIA      9000000211      NOIDA      yes                  2
13    Arjun Mishra    919000000106  new delhi       No                 10
15     Isha Kapoor  +91-9000000295  New Delhi      yes                  6
16     Isha Chopra    919000000138       pune       No                  7
17    MEERA BHATIA    919000000223      Delhi       No                  4
18   Vikram Saxena      9000000113    Gurgaon       No                 15
19    Rahul Chopra      9000000137     Noida         N                 10
20     Tanvi Gupta      9000000254  Bengaluru       No                 14
21    VARUN SAXENA    919000000170    GURGAON        Y                  1
22    Sneha Chopra  +91-9000000162       pune        N                 14
23     DEEPAK NAIR    919000000296  Bengaluru      Yes                  2
24    Gaurav Mehta      9000000133  Bengaluru        N                  1
25     Neha Bhatia      9000000273       PUNE       No                 10
26     Arjun Mehta      9000000272      Noida      Yes                 14
27   MANISH BHATIA    919000000161     Noida       Yes                  5
28    DIVYA CHOPRA      9000000111      NOIDA        N                  5
29    Karan Chopra    919000000245       pune        N                 10
30    Vikram Mehta  +91-9000000261       PUNE        Y                  2

In [36]:
def normalize_verfied(value):
    if pd.isna(value):
        return value
    value=str(value).strip().lower()
    if value in ["yes","verified","y"]:
        return "Y"
    elif value in ["no","n"]:
        return "N"
    else:
        return value

cbnexus_contacts_df["Verified"]=cbnexus_contacts_df["Verified"].apply(normalize_verfied)
cbnexus_contacts_df

              Name    Phone Number       City Verified Projects Completed
0       Rohit Nair      9000000268    Gurgaon        Y                 13
1      RITU SHARMA      9000000146     Noida         Y                 15
2     Priya Saxena    919000000231  New Delhi        N                 12
3      Arjun Mehta  +91-9000000131      Noida        N                  9
4     Nikhil Mehta  +91-9000000104       pune        Y                 10
5   RAHUL MALHOTRA    919000000260  Delhi NCR        N                  4
6     Deepak Mehta      9000000116      Noida        Y                 11
7   SAHIL MALHOTRA      9000000143      Noida        N                  0
8     Shreya Gupta  +91-9000000227      NOIDA        Y                 13
9      Priya Singh      9000000287  gurugram         Y                  3
10      Varun Jain    919000000263       Pune        Y                 14
11   Tanvi Agarwal    919000000148       Pune        N                  3
12    KARAN BHATIA      9000000211      NOIDA        Y                  2
13    Arjun Mishra    919000000106  new delhi        N                 10
15     Isha Kapoor  +91-9000000295  New Delhi        Y                  6
16     Isha Chopra    919000000138       pune        N                  7
17    MEERA BHATIA    919000000223      Delhi        N                  4
18   Vikram Saxena      9000000113    Gurgaon        N                 15
19    Rahul Chopra      9000000137     Noida         N                 10
20     Tanvi Gupta      9000000254  Bengaluru        N                 14
21    VARUN SAXENA    919000000170    GURGAON        Y                  1
22    Sneha Chopra  +91-9000000162       pune        N                 14
23     DEEPAK NAIR    919000000296  Bengaluru        Y                  2
24    Gaurav Mehta      9000000133  Bengaluru        N                  1
25     Neha Bhatia      9000000273       PUNE        N                 10
26     Arjun Mehta      9000000272      Noida        Y                 14
27   MANISH BHATIA    919000000161     Noida         Y                  5
28    DIVYA CHOPRA      9000000111      NOIDA        N                  5
29    Karan Chopra    919000000245       pune        N                 10
30    Vikram Mehta  +91-9000000261       PUNE        Y                  2

In [46]:
cbnexus_contacts_df["City"]=cbnexus_contacts_df["City"].str.title()
cbnexus_contacts_df

              Name Phone Number       City Verified Projects Completed
0       Rohit Nair   9000000268    Gurgaon        Y                 13
1      Ritu Sharma   9000000146     Noida         Y                 15
2     Priya Saxena   9000000231  New Delhi        N                 12
3      Arjun Mehta   9000000131      Noida        N                  9
4     Nikhil Mehta   9000000104       Pune        Y                 10
5   Rahul Malhotra   9000000260  Delhi Ncr        N                  4
6     Deepak Mehta   9000000116      Noida        Y                 11
7   Sahil Malhotra   9000000143      Noida        N                  0
8     Shreya Gupta   9000000227      Noida        Y                 13
9      Priya Singh   9000000287  Gurugram         Y                  3
10      Varun Jain   9000000263       Pune        Y                 14
11   Tanvi Agarwal   9000000148       Pune        N                  3
12    Karan Bhatia   9000000211      Noida        Y                  2
13    Arjun Mishra   9000000106  New Delhi        N                 10
15     Isha Kapoor   9000000295  New Delhi        Y                  6
16     Isha Chopra   9000000138       Pune        N                  7
17    Meera Bhatia   9000000223      Delhi        N                  4
18   Vikram Saxena   9000000113    Gurgaon        N                 15
19    Rahul Chopra   9000000137     Noida         N                 10
20     Tanvi Gupta   9000000254  Bengaluru        N                 14
21    Varun Saxena   9000000170    Gurgaon        Y                  1
22    Sneha Chopra   9000000162       Pune        N                 14
23     Deepak Nair   9000000296  Bengaluru        Y                  2
24    Gaurav Mehta   9000000133  Bengaluru        N                  1
25     Neha Bhatia   9000000273       Pune        N                 10
26     Arjun Mehta   9000000272      Noida        Y                 14
27   Manish Bhatia   9000000161     Noida         Y                  5
28    Divya Chopra   9000000111      Noida        N                  5
29    Karan Chopra   9000000245       Pune        N                 10
30    Vikram Mehta   9000000261       Pune        Y                  2

In [41]:
import re
def normalize_phone(value):
    if pd.isna(value):
        return value
    phone=str(value).strip()
    phone=re.sub(r"\D","",phone)

    if phone.startswith("91")and len(phone)==12:
        phone=phone[2:]
    return phone
cbnexus_contacts_df["Phone Number"]=cbnexus_contacts_df["Phone Number"].apply(normalize_phone)
cbnexus_contacts_df

              Name Phone Number       City Verified Projects Completed
0       Rohit Nair   9000000268    Gurgaon        Y                 13
1      RITU SHARMA   9000000146     Noida         Y                 15
2     Priya Saxena   9000000231  New delhi        N                 12
3      Arjun Mehta   9000000131      Noida        N                  9
4     Nikhil Mehta   9000000104       Pune        Y                 10
5   RAHUL MALHOTRA   9000000260  Delhi ncr        N                  4
6     Deepak Mehta   9000000116      Noida        Y                 11
7   SAHIL MALHOTRA   9000000143      Noida        N                  0
8     Shreya Gupta   9000000227      Noida        Y                 13
9      Priya Singh   9000000287  Gurugram         Y                  3
10      Varun Jain   9000000263       Pune        Y                 14
11   Tanvi Agarwal   9000000148       Pune        N                  3
12    KARAN BHATIA   9000000211      Noida        Y                  2
13    Arjun Mishra   9000000106  New delhi        N                 10
15     Isha Kapoor   9000000295  New delhi        Y                  6
16     Isha Chopra   9000000138       Pune        N                  7
17    MEERA BHATIA   9000000223      Delhi        N                  4
18   Vikram Saxena   9000000113    Gurgaon        N                 15
19    Rahul Chopra   9000000137     Noida         N                 10
20     Tanvi Gupta   9000000254  Bengaluru        N                 14
21    VARUN SAXENA   9000000170    Gurgaon        Y                  1
22    Sneha Chopra   9000000162       Pune        N                 14
23     DEEPAK NAIR   9000000296  Bengaluru        Y                  2
24    Gaurav Mehta   9000000133  Bengaluru        N                  1
25     Neha Bhatia   9000000273       Pune        N                 10
26     Arjun Mehta   9000000272      Noida        Y                 14
27   MANISH BHATIA   9000000161     Noida         Y                  5
28    DIVYA CHOPRA   9000000111      Noida        N                  5
29    Karan Chopra   9000000245       Pune        N                 10
30    Vikram Mehta   9000000261       Pune        Y                  2

In [44]:
cbnexus_contacts_df["Name"]=cbnexus_contacts_df["Name"].str.title()
cbnexus_contacts_df

              Name Phone Number       City Verified Projects Completed
0       Rohit Nair   9000000268    Gurgaon        Y                 13
1      Ritu Sharma   9000000146     Noida         Y                 15
2     Priya Saxena   9000000231  New delhi        N                 12
3      Arjun Mehta   9000000131      Noida        N                  9
4     Nikhil Mehta   9000000104       Pune        Y                 10
5   Rahul Malhotra   9000000260  Delhi ncr        N                  4
6     Deepak Mehta   9000000116      Noida        Y                 11
7   Sahil Malhotra   9000000143      Noida        N                  0
8     Shreya Gupta   9000000227      Noida        Y                 13
9      Priya Singh   9000000287  Gurugram         Y                  3
10      Varun Jain   9000000263       Pune        Y                 14
11   Tanvi Agarwal   9000000148       Pune        N                  3
12    Karan Bhatia   9000000211      Noida        Y                  2
13    Arjun Mishra   9000000106  New delhi        N                 10
15     Isha Kapoor   9000000295  New delhi        Y                  6
16     Isha Chopra   9000000138       Pune        N                  7
17    Meera Bhatia   9000000223      Delhi        N                  4
18   Vikram Saxena   9000000113    Gurgaon        N                 15
19    Rahul Chopra   9000000137     Noida         N                 10
20     Tanvi Gupta   9000000254  Bengaluru        N                 14
21    Varun Saxena   9000000170    Gurgaon        Y                  1
22    Sneha Chopra   9000000162       Pune        N                 14
23     Deepak Nair   9000000296  Bengaluru        Y                  2
24    Gaurav Mehta   9000000133  Bengaluru        N                  1
25     Neha Bhatia   9000000273       Pune        N                 10
26     Arjun Mehta   9000000272      Noida        Y                 14
27   Manish Bhatia   9000000161     Noida         Y                  5
28    Divya Chopra   9000000111      Noida        N                  5
29    Karan Chopra   9000000245       Pune        N                 10
30    Vikram Mehta   9000000261       Pune        Y                  2

In [45]:
naukri_df

,Full Name,Email,Phone,City,Experience (Years),Current CTC,Applied Date,Skills
0,Tanvi Gupta,tanvi.gupta31@example.com,919000000254,Bengaluru,4.2,417964.0,24-07-2026,"n8n, LangChain, REST APIs, MongoDB, SQL"
1,Manish Reddy,manish.reddy73@example.com,9000000237,GURGAON,3.5,332456.0,2026-08-08,"Docker, Zapier, JavaScript"
2,Priya Singh,priya.singh61@mailtest.example.org,9000000287,GURGAON,3.0,775670.0,01-08-2026,"React, Zapier, n8n, MySQL, Python, SQL"
3,Vikram Saxena,vikram.saxena60@example.com,9000000113,GURGAON,1.9,654699.0,7 Jul 2026,"Selenium, Web Scraping, React, Docker, SQL, Fa..."
4,Amit Agarwal,amit.agarwal3@mailtest.example.org,919000000288,pune,1.8,4.2,19-07-2026,"SQL, Python, JavaScript, Docker"
5,Sahil Malhotra,sahil.malhotra1@example.in,919000000143,Noida,1.7,806661.0,07/13/2026,"FastAPI, Docker, MySQL, Zapier, Pandas, REST APIs"
6,Shreya Gupta,shreya.gupta85@example.com,9000000227,NOIDA,3.3,8.3,19 Jul 2026,"Zapier, Web Scraping, Docker, n8n, Python"
7,Isha Chopra,isha.chopra95@mailtest.example.org,9000000138,PUNE,5.4,472935.0,2026-08-02,"React, JavaScript, MySQL"
8,Priya Nair,priya.nair70@example.com,919000000222,gurugram,5.6,366311.0,28-07-2026,"Zapier, REST APIs, React, Python, n8n, Web Scr..."
9,Rohit Mishra,rohit.mishra70@mailtest.example.org,9000000167,Delhi,4.4,871686.0,2026-07-13,"Docker, Pandas, FastAPI, SQL, Zapier, MySQL"
10,Rahul Malhotra,rahul.malhotra69@mailtest.example.org,9000000260,new delhi,2.5,864237.0,07/03/2026,"MySQL, REST APIs, SQL, MongoDB, Selenium"
11,Rahul Jain,rahul.jain34@example.in,9000000114,Noida,2.8,1195422.0,2026-06-24,"Zapier, Selenium, Docker, Python"
12,Nikhil Malhotra,nikhil.malhotra41@example.in,9000000145,New Delhi,4.2,5.1,21-08-2026,"FastAPI, JavaScript, Web Scraping, SQL, Python"
13,Karan Bhatia,karan.bhatia32@mailtest.example.org,919000000211,Noida,4.7,826748.0,8 Jul 2026,"SQL, MongoDB, Selenium, Zapier, Web Scraping, ..."
14,Ritu Sharma,ritu.sharma23@mailtest.example.org,9000000146,Noida,4.8,6.1,2026-08-03,"n8n, Web Scraping, MongoDB, SQL, React"
15,Arjun Mishra,arjun.mishra70@example.com,9000000106,Delhi,1.3,5.8,22-08-2026,"React, Docker, JavaScript"
16,Meera Bhatia,meera.bhatia52@mailtest.example.org,9000000223,Delhi NCR,5.1,11.2,2026-07-03,"LangChain, Docker, MySQL, Python, SQL, React"
17,Varun Jain,varun.jain29@example.com,9000000263,Pune,3.1,7.6,08/19/2026,"n8n, Web Scraping, FastAPI, MySQL, Pandas, Mon..."
18,Arjun Mehta,arjun.mehta9@example.in,9000000131,NOIDA,4.0,1181149.0,21-07-2026,"SQL, Selenium, n8n"
19,Kavya Mehta,kavya.mehta7@example.com,919000000177,Bengaluru,5.1,2.4,2 Jul 2026,"n8n, MongoDB, FastAPI, Pandas, React"
20,Sneha Chopra,sneha.chopra99@example.in,919000000162,pune,4.9,10.0,03-07-2026,"Pandas, React, MySQL, JavaScript, SQL"
21,Deepak Mehta,deepak.mehta86@example.in,9000000116,NOIDA,2.7,327287.0,2026-07-23,"MySQL, MongoDB, n8n, LangChain, REST APIs, Sel..."
22,Pooja Gupta,pooja.gupta57@mailtest.example.org,9000000271,Noida,3.9,11.9,24-06-2026,"Docker, MySQL, SQL, n8n, Selenium"
23,R. Verma,rohit.verma13@mailtest.example.org,9000000294,Bangalore,2.4,6.1,08/13/2026,"Python, React, MongoDB"
24,Sneha Mishra,sneha.mishra14@mailtest.example.org,9000000229,pune,1.4,410629.0,15-06-2026,"MySQL, Docker, Selenium, Pandas"
25,Nikhil Chopra,alt.nikhil.chopra70@example.com,9000000103,NOIDA,0.8,7.8,07/03/2026,"Pandas, SQL, n8n"
26,Priya Saxena,priya.saxena61@example.com,919000000231,Delhi,5.0,6.6,08/16/2026,"Python, MySQL, Zapier, React"
27,Varun Saxena,varun.saxena21@example.in,9000000170,gurugram,3.7,775796.0,5 Jul 2026,"MongoDB, Zapier, SQL, LangChain, MySQL, REST APIs"
28,Gaurav Mehta,gaurav.mehta79@mailtest.example.org,9000000133,Bengaluru,3.1,792474.0,19-07-2026,"REST APIs, SQL, Selenium, FastAPI"
29,Rohit Verma,rohit.verma13@mailtest.example.org,9000000294,Bangalore,2.4,6.1,08/13/2026,"Python, React, MongoDB"
30,Rohit Nair,rohit.nair32@mailtest.example.org,919000000268,Gurugram,2.4,7.6,2026-08-19,"REST APIs, n8n, Web Scraping, Docker"
31,Deepak Nair,deepak.nair44@example.com,9000000296,bangalore,5.0,1160787.0,15 Jul 2026,"React, n8n, MongoDB, Pandas"
32,Rahul Chopra,rahul.chopra70@example.com,9000000137,NOIDA,1.7,2.7,27 Jul 2026,"Zapier, Docker, Python"
33,Deepak Singh,deepak.singh36@mailtest.example.org,9000000202,bangalore,1.7,1135514.0,08/11/2026,"Web Scraping, FastAPI, Docker, React"
34,Amit Reddy,amit.reddy9@mailtest.example.org,9000000165,Delhi NCR,2.7,11.4,21 Jul 2026,"React, MySQL, LangChain"
35,Nikhil Chopra,nikhil.chopra70@example.com,9000000103,NOIDA,0.8,7.8,07/03/2026,"Pandas, SQL, n8n"
36,Tanvi Agarwal,tanvi.agarwal97@example.in,919000000148,PUNE,5.0,626740.0,27 Jul 2026,"MongoDB, REST APIs, FastAPI, Web Scraping"
37,Nikhil Mehta,nikhil.mehta5@example.com,9000000104,PUNE,2.9,9.3,2026-07-26,"Docker, LangChain, Zapier, Selenium, Python, R..."
38,Isha Kapoor,isha.kapoor54@example.com,919000000295,new delhi,5.1,5.9,08/21/2026,"FastAPI, Python, JavaScript, Selenium, React, ..."
39,Arjun Bhatia,arjun.bhatia14@example.com,9000000212,new delhi,1.5,621881.0,02-06-2026,"Zapier, REST APIs, SQL, FastAPI, Pandas, Web S..."
40,Isha Sharma,isha.sharma15@example.com,919000000259,Delhi,3.5,10.3,07/12/2026,"n8n, Python, Selenium, JavaScript, REST APIs, ..."
41,Neha Bhatia,neha.bhatia60@mailtest.example.org,9000000273,Pune,4.2,694306.0,22 Jul 2026,"FastAPI, Zapier, JavaScript, Selenium"

In [53]:
naukri_df["Phone"]=naukri_df["Phone"].apply(normalize_phone)
naukri_df["City"]=naukri_df["City"].str.title()
naukri_df

,Full Name,Email,Phone,City,Experience (Years),Current CTC,Applied Date,Skills
0,Tanvi Gupta,tanvi.gupta31@example.com,9000000254,Bengaluru,4.2,417964.0,24-07-2026,"n8n, LangChain, REST APIs, MongoDB, SQL"
1,Manish Reddy,manish.reddy73@example.com,9000000237,Gurgaon,3.5,332456.0,2026-08-08,"Docker, Zapier, JavaScript"
2,Priya Singh,priya.singh61@mailtest.example.org,9000000287,Gurgaon,3.0,775670.0,01-08-2026,"React, Zapier, n8n, MySQL, Python, SQL"
3,Vikram Saxena,vikram.saxena60@example.com,9000000113,Gurgaon,1.9,654699.0,7 Jul 2026,"Selenium, Web Scraping, React, Docker, SQL, Fa..."
4,Amit Agarwal,amit.agarwal3@mailtest.example.org,9000000288,Pune,1.8,4.2,19-07-2026,"SQL, Python, JavaScript, Docker"
5,Sahil Malhotra,sahil.malhotra1@example.in,9000000143,Noida,1.7,806661.0,07/13/2026,"FastAPI, Docker, MySQL, Zapier, Pandas, REST APIs"
6,Shreya Gupta,shreya.gupta85@example.com,9000000227,Noida,3.3,8.3,19 Jul 2026,"Zapier, Web Scraping, Docker, n8n, Python"
7,Isha Chopra,isha.chopra95@mailtest.example.org,9000000138,Pune,5.4,472935.0,2026-08-02,"React, JavaScript, MySQL"
8,Priya Nair,priya.nair70@example.com,9000000222,Gurugram,5.6,366311.0,28-07-2026,"Zapier, REST APIs, React, Python, n8n, Web Scr..."
9,Rohit Mishra,rohit.mishra70@mailtest.example.org,9000000167,Delhi,4.4,871686.0,2026-07-13,"Docker, Pandas, FastAPI, SQL, Zapier, MySQL"
10,Rahul Malhotra,rahul.malhotra69@mailtest.example.org,9000000260,New Delhi,2.5,864237.0,07/03/2026,"MySQL, REST APIs, SQL, MongoDB, Selenium"
11,Rahul Jain,rahul.jain34@example.in,9000000114,Noida,2.8,1195422.0,2026-06-24,"Zapier, Selenium, Docker, Python"
12,Nikhil Malhotra,nikhil.malhotra41@example.in,9000000145,New Delhi,4.2,5.1,21-08-2026,"FastAPI, JavaScript, Web Scraping, SQL, Python"
13,Karan Bhatia,karan.bhatia32@mailtest.example.org,9000000211,Noida,4.7,826748.0,8 Jul 2026,"SQL, MongoDB, Selenium, Zapier, Web Scraping, ..."
14,Ritu Sharma,ritu.sharma23@mailtest.example.org,9000000146,Noida,4.8,6.1,2026-08-03,"n8n, Web Scraping, MongoDB, SQL, React"
15,Arjun Mishra,arjun.mishra70@example.com,9000000106,Delhi,1.3,5.8,22-08-2026,"React, Docker, JavaScript"
16,Meera Bhatia,meera.bhatia52@mailtest.example.org,9000000223,Delhi Ncr,5.1,11.2,2026-07-03,"LangChain, Docker, MySQL, Python, SQL, React"
17,Varun Jain,varun.jain29@example.com,9000000263,Pune,3.1,7.6,08/19/2026,"n8n, Web Scraping, FastAPI, MySQL, Pandas, Mon..."
18,Arjun Mehta,arjun.mehta9@example.in,9000000131,Noida,4.0,1181149.0,21-07-2026,"SQL, Selenium, n8n"
19,Kavya Mehta,kavya.mehta7@example.com,9000000177,Bengaluru,5.1,2.4,2 Jul 2026,"n8n, MongoDB, FastAPI, Pandas, React"
20,Sneha Chopra,sneha.chopra99@example.in,9000000162,Pune,4.9,10.0,03-07-2026,"Pandas, React, MySQL, JavaScript, SQL"
21,Deepak Mehta,deepak.mehta86@example.in,9000000116,Noida,2.7,327287.0,2026-07-23,"MySQL, MongoDB, n8n, LangChain, REST APIs, Sel..."
22,Pooja Gupta,pooja.gupta57@mailtest.example.org,9000000271,Noida,3.9,11.9,24-06-2026,"Docker, MySQL, SQL, n8n, Selenium"
23,R. Verma,rohit.verma13@mailtest.example.org,9000000294,Bangalore,2.4,6.1,08/13/2026,"Python, React, MongoDB"
24,Sneha Mishra,sneha.mishra14@mailtest.example.org,9000000229,Pune,1.4,410629.0,15-06-2026,"MySQL, Docker, Selenium, Pandas"
25,Nikhil Chopra,alt.nikhil.chopra70@example.com,9000000103,Noida,0.8,7.8,07/03/2026,"Pandas, SQL, n8n"
26,Priya Saxena,priya.saxena61@example.com,9000000231,Delhi,5.0,6.6,08/16/2026,"Python, MySQL, Zapier, React"
27,Varun Saxena,varun.saxena21@example.in,9000000170,Gurugram,3.7,775796.0,5 Jul 2026,"MongoDB, Zapier, SQL, LangChain, MySQL, REST APIs"
28,Gaurav Mehta,gaurav.mehta79@mailtest.example.org,9000000133,Bengaluru,3.1,792474.0,19-07-2026,"REST APIs, SQL, Selenium, FastAPI"
29,Rohit Verma,rohit.verma13@mailtest.example.org,9000000294,Bangalore,2.4,6.1,08/13/2026,"Python, React, MongoDB"
30,Rohit Nair,rohit.nair32@mailtest.example.org,9000000268,Gurugram,2.4,7.6,2026-08-19,"REST APIs, n8n, Web Scraping, Docker"
31,Deepak Nair,deepak.nair44@example.com,9000000296,Bangalore,5.0,1160787.0,15 Jul 2026,"React, n8n, MongoDB, Pandas"
32,Rahul Chopra,rahul.chopra70@example.com,9000000137,Noida,1.7,2.7,27 Jul 2026,"Zapier, Docker, Python"
33,Deepak Singh,deepak.singh36@mailtest.example.org,9000000202,Bangalore,1.7,1135514.0,08/11/2026,"Web Scraping, FastAPI, Docker, React"
34,Amit Reddy,amit.reddy9@mailtest.example.org,9000000165,Delhi Ncr,2.7,11.4,21 Jul 2026,"React, MySQL, LangChain"
35,Nikhil Chopra,nikhil.chopra70@example.com,9000000103,Noida,0.8,7.8,07/03/2026,"Pandas, SQL, n8n"
36,Tanvi Agarwal,tanvi.agarwal97@example.in,9000000148,Pune,5.0,626740.0,27 Jul 2026,"MongoDB, REST APIs, FastAPI, Web Scraping"
37,Nikhil Mehta,nikhil.mehta5@example.com,9000000104,Pune,2.9,9.3,2026-07-26,"Docker, LangChain, Zapier, Selenium, Python, R..."
38,Isha Kapoor,isha.kapoor54@example.com,9000000295,New Delhi,5.1,5.9,08/21/2026,"FastAPI, Python, JavaScript, Selenium, React, ..."
39,Arjun Bhatia,arjun.bhatia14@example.com,9000000212,New Delhi,1.5,621881.0,02-06-2026,"Zapier, REST APIs, SQL, FastAPI, Pandas, Web S..."
40,Isha Sharma,isha.sharma15@example.com,9000000259,Delhi,3.5,10.3,07/12/2026,"n8n, Python, Selenium, JavaScript, REST APIs, ..."
41,Neha Bhatia,neha.bhatia60@mailtest.example.org,9000000273,Pune,4.2,694306.0,22 Jul 2026,"FastAPI, Zapier, JavaScript, Selenium"

In [63]:
def normalize_date(value):
    if pd.isna(value):
        return pd.NaT

    value = str(value).strip()

    formats = [
        "%d-%m-%Y",   # 24-07-2026
        "%d/%m/%Y",   # 24/07/2026
        "%m/%d/%Y",   # 07/13/2026
        "%d %b %Y",   # 7 Jul 2026
        "%d %B %Y"    # 7 July 2026
    ]

    for fmt in formats:
        try:
            return pd.to_datetime(value, format=fmt)
        except (ValueError, TypeError):
            pass

    # If nothing matched, keep the original value
    return value
naukri_df["Applied Date"]=naukri_df["Applied Date"].apply(normalize_date)
naukri_df["Applied Date"] = pd.to_datetime(
    naukri_df["Applied Date"],
    format="mixed"
).dt.date
naukri_df

,Full Name,Email,Phone,City,Experience (Years),Current CTC,Applied Date,Skills
0,Tanvi Gupta,tanvi.gupta31@example.com,9000000254,Bengaluru,4.2,417964.0,2026-07-24,"n8n, LangChain, REST APIs, MongoDB, SQL"
1,Manish Reddy,manish.reddy73@example.com,9000000237,Gurgaon,3.5,332456.0,2026-08-08,"Docker, Zapier, JavaScript"
2,Priya Singh,priya.singh61@mailtest.example.org,9000000287,Gurgaon,3.0,775670.0,2026-08-01,"React, Zapier, n8n, MySQL, Python, SQL"
3,Vikram Saxena,vikram.saxena60@example.com,9000000113,Gurgaon,1.9,654699.0,2026-07-07,"Selenium, Web Scraping, React, Docker, SQL, Fa..."
4,Amit Agarwal,amit.agarwal3@mailtest.example.org,9000000288,Pune,1.8,4.2,2026-07-19,"SQL, Python, JavaScript, Docker"
5,Sahil Malhotra,sahil.malhotra1@example.in,9000000143,Noida,1.7,806661.0,2026-07-13,"FastAPI, Docker, MySQL, Zapier, Pandas, REST APIs"
6,Shreya Gupta,shreya.gupta85@example.com,9000000227,Noida,3.3,8.3,2026-07-19,"Zapier, Web Scraping, Docker, n8n, Python"
7,Isha Chopra,isha.chopra95@mailtest.example.org,9000000138,Pune,5.4,472935.0,2026-08-02,"React, JavaScript, MySQL"
8,Priya Nair,priya.nair70@example.com,9000000222,Gurugram,5.6,366311.0,2026-07-28,"Zapier, REST APIs, React, Python, n8n, Web Scr..."
9,Rohit Mishra,rohit.mishra70@mailtest.example.org,9000000167,Delhi,4.4,871686.0,2026-07-13,"Docker, Pandas, FastAPI, SQL, Zapier, MySQL"
10,Rahul Malhotra,rahul.malhotra69@mailtest.example.org,9000000260,New Delhi,2.5,864237.0,2026-03-07,"MySQL, REST APIs, SQL, MongoDB, Selenium"
11,Rahul Jain,rahul.jain34@example.in,9000000114,Noida,2.8,1195422.0,2026-06-24,"Zapier, Selenium, Docker, Python"
12,Nikhil Malhotra,nikhil.malhotra41@example.in,9000000145,New Delhi,4.2,5.1,2026-08-21,"FastAPI, JavaScript, Web Scraping, SQL, Python"
13,Karan Bhatia,karan.bhatia32@mailtest.example.org,9000000211,Noida,4.7,826748.0,2026-07-08,"SQL, MongoDB, Selenium, Zapier, Web Scraping, ..."
14,Ritu Sharma,ritu.sharma23@mailtest.example.org,9000000146,Noida,4.8,6.1,2026-08-03,"n8n, Web Scraping, MongoDB, SQL, React"
15,Arjun Mishra,arjun.mishra70@example.com,9000000106,Delhi,1.3,5.8,2026-08-22,"React, Docker, JavaScript"
16,Meera Bhatia,meera.bhatia52@mailtest.example.org,9000000223,Delhi Ncr,5.1,11.2,2026-07-03,"LangChain, Docker, MySQL, Python, SQL, React"
17,Varun Jain,varun.jain29@example.com,9000000263,Pune,3.1,7.6,2026-08-19,"n8n, Web Scraping, FastAPI, MySQL, Pandas, Mon..."
18,Arjun Mehta,arjun.mehta9@example.in,9000000131,Noida,4.0,1181149.0,2026-07-21,"SQL, Selenium, n8n"
19,Kavya Mehta,kavya.mehta7@example.com,9000000177,Bengaluru,5.1,2.4,2026-07-02,"n8n, MongoDB, FastAPI, Pandas, React"
20,Sneha Chopra,sneha.chopra99@example.in,9000000162,Pune,4.9,10.0,2026-07-03,"Pandas, React, MySQL, JavaScript, SQL"
21,Deepak Mehta,deepak.mehta86@example.in,9000000116,Noida,2.7,327287.0,2026-07-23,"MySQL, MongoDB, n8n, LangChain, REST APIs, Sel..."
22,Pooja Gupta,pooja.gupta57@mailtest.example.org,9000000271,Noida,3.9,11.9,2026-06-24,"Docker, MySQL, SQL, n8n, Selenium"
23,R. Verma,rohit.verma13@mailtest.example.org,9000000294,Bangalore,2.4,6.1,2026-08-13,"Python, React, MongoDB"
24,Sneha Mishra,sneha.mishra14@mailtest.example.org,9000000229,Pune,1.4,410629.0,2026-06-15,"MySQL, Docker, Selenium, Pandas"
25,Nikhil Chopra,alt.nikhil.chopra70@example.com,9000000103,Noida,0.8,7.8,2026-03-07,"Pandas, SQL, n8n"
26,Priya Saxena,priya.saxena61@example.com,9000000231,Delhi,5.0,6.6,2026-08-16,"Python, MySQL, Zapier, React"
27,Varun Saxena,varun.saxena21@example.in,9000000170,Gurugram,3.7,775796.0,2026-07-05,"MongoDB, Zapier, SQL, LangChain, MySQL, REST APIs"
28,Gaurav Mehta,gaurav.mehta79@mailtest.example.org,9000000133,Bengaluru,3.1,792474.0,2026-07-19,"REST APIs, SQL, Selenium, FastAPI"
29,Rohit Verma,rohit.verma13@mailtest.example.org,9000000294,Bangalore,2.4,6.1,2026-08-13,"Python, React, MongoDB"
30,Rohit Nair,rohit.nair32@mailtest.example.org,9000000268,Gurugram,2.4,7.6,2026-08-19,"REST APIs, n8n, Web Scraping, Docker"
31,Deepak Nair,deepak.nair44@example.com,9000000296,Bangalore,5.0,1160787.0,2026-07-15,"React, n8n, MongoDB, Pandas"
32,Rahul Chopra,rahul.chopra70@example.com,9000000137,Noida,1.7,2.7,2026-07-27,"Zapier, Docker, Python"
33,Deepak Singh,deepak.singh36@mailtest.example.org,9000000202,Bangalore,1.7,1135514.0,2026-11-08,"Web Scraping, FastAPI, Docker, React"
34,Amit Reddy,amit.reddy9@mailtest.example.org,9000000165,Delhi Ncr,2.7,11.4,2026-07-21,"React, MySQL, LangChain"
35,Nikhil Chopra,nikhil.chopra70@example.com,9000000103,Noida,0.8,7.8,2026-03-07,"Pandas, SQL, n8n"
36,Tanvi Agarwal,tanvi.agarwal97@example.in,9000000148,Pune,5.0,626740.0,2026-07-27,"MongoDB, REST APIs, FastAPI, Web Scraping"
37,Nikhil Mehta,nikhil.mehta5@example.com,9000000104,Pune,2.9,9.3,2026-07-26,"Docker, LangChain, Zapier, Selenium, Python, R..."
38,Isha Kapoor,isha.kapoor54@example.com,9000000295,New Delhi,5.1,5.9,2026-08-21,"FastAPI, Python, JavaScript, Selenium, React, ..."
39,Arjun Bhatia,arjun.bhatia14@example.com,9000000212,New Delhi,1.5,621881.0,2026-06-02,"Zapier, REST APIs, SQL, FastAPI, Pandas, Web S..."
40,Isha Sharma,isha.sharma15@example.com,9000000259,Delhi,3.5,10.3,2026-12-07,"n8n, Python, Selenium, JavaScript, REST APIs, ..."
41,Neha Bhatia,neha.bhatia60@mailtest.example.org,9000000273,Pune,4.2,694306.0,2026-07-22,"FastAPI, Zapier, JavaScript, Selenium"

In [64]:
gig_workers_df

,email_id,worker_name,rate,location,status,skill_tags
0,varun.jain29@example.com,Varun Jain,1415/hr,Pune,Active,"n8n, web scraping, fastapi, mysql, pandas, mon..."
1,tanvi.agarwal97@example.in,Tanvi Agarwal,1231/hr,PUNE,Active,"mongodb, rest apis, fastapi, web scraping"
2,karan.bhatia32@mailtest.example.org,Karan Bhatia,403/hr,Noida,active,"sql, mongodb, selenium, zapier, web scraping, ..."
3,arjun.mishra70@example.com,Arjun Mishra,440/hr,Delhi,ACTIVE,"react, docker, javascript"
4,isha.kapoor54@example.com,Isha Kapoor,15k/month,Delhi,active,"fastapi, python, javascript, selenium, react, ..."
5,ISHA.CHOPRA95@MAILTEST.EXAMPLE.ORG,Isha Chopra,1406/hr,Pune,active,"react, javascript, mysql"
6,meera.bhatia52@mailtest.example.org,Meera Bhatia,330/hr,New Delhi,active,"langchain, docker, mysql, python, sql, react"
7,vikram.saxena60@example.com,Vikram Saxena,843/hr,Gurgaon,Active,"selenium, web scraping, react, docker, sql, fa..."
8,rahul.chopra70@example.com,Rahul Chopra,72k/month,Noida,Inactive,"zapier, docker, python"
9,tanvi.gupta31@example.com,Tanvi Gupta,1331/hr,bangalore,paused,"n8n, langchain, rest apis, mongodb, sql"
11,VARUN.SAXENA21@EXAMPLE.IN,Varun Saxena,917/hr,gurugram,Inactive,"mongodb, zapier, sql, langchain, mysql, rest apis"
12,sneha.chopra99@example.in,Sneha Chopra,28k/month,pune,Active,"pandas, react, mysql, javascript, sql"
13,DEEPAK.NAIR44@EXAMPLE.COM,Deepak Nair,465/hr,Bengaluru,paused,"react, n8n, mongodb, pandas"
14,gaurav.mehta79@mailtest.example.org,Gaurav Mehta,56k/month,bangalore,ACTIVE,"rest apis, sql, selenium, fastapi"
15,NEHA.BHATIA60@MAILTEST.EXAMPLE.ORG,Neha Bhatia,79k/month,PUNE,Active,"fastapi, zapier, javascript, selenium"
16,arjun.mehta77@mailtest.example.org,Arjun Mehta,42k/month,Noida,Inactive,"fastapi, pandas, web scraping, zapier, docker,..."
17,manish.bhatia3@example.com,Manish Bhatia,73k/month,Noida,ACTIVE,"pandas, docker, javascript, react, rest apis, ..."
18,"react, javascript, mysql",ISHA.CHOPRA95@MAILTEST.EXAMPLE.ORG,Isha Chopra,1406/hr,Pune,active
19,divya.chopra59@example.in,Divya Chopra,55k/month,Noida,Inactive,"zapier, docker, mongodb, fastapi"
20,KARAN.CHOPRA76@MAILTEST.EXAMPLE.ORG,Karan Chopra,437/hr,Pune,ACTIVE,"n8n, selenium, python, mongodb, pandas"
21,vikram.mehta6@example.com,Vikram Mehta,22k/month,pune,ACTIVE,"rest apis, python, langchain"
22,pooja.kapoor62@example.in,Pooja Kapoor,21k/month,NOIDA,Active,"rest apis, sql, react"
23,KAVYA.VERMA74@MAILTEST.EXAMPLE.ORG,Kavya Verma,1483/hr,gurugram,active,"sql, pandas, web scraping, react"
24,TANVI.REDDY80@EXAMPLE.COM,Tanvi Reddy,59k/month,pune,paused,"langchain, docker, python, rest apis, sql"
25,varun.singh81@example.com,Varun Singh,763/hr,Noida,ACTIVE,"python, react, fastapi, mongodb"
26,tanvi.kapoor38@example.com,Tanvi Kapoor,38k/month,new delhi,ACTIVE,"docker, selenium, web scraping, mysql"
27,nikhil.nair26@example.in,Nikhil Nair,1018/hr,gurugram,Active,"python, n8n, web scraping"
28,pooja.reddy96@mailtest.example.org,Pooja Reddy,590/hr,Noida,Inactive,"pandas, docker, fastapi, web scraping, sql"
29,TANVI.SHARMA56@MAILTEST.EXAMPLE.ORG,Tanvi Sharma,73k/month,NOIDA,ACTIVE,"langchain, python, web scraping, n8n, fastapi"
30,DEEPAK.NAIR57@EXAMPLE.IN,Deepak Nair,1462/hr,New Delhi,Active,"javascript, react, docker, web scraping, mysql..."
31,anjali.agarwal53@mailtest.example.org,Anjali Agarwal,71k/month,Bengaluru,Inactive,"sql, javascript, selenium, rest apis, docker, ..."

In [83]:
gig_workers_df

,email_id,worker_name,rate,location,status,skill_tags
0,varun.jain29@example.com,Varun Jain,1415/hr,Pune,Active,"n8n, web scraping, fastapi, mysql, pandas, mon..."
1,tanvi.agarwal97@example.in,Tanvi Agarwal,1231/hr,PUNE,Active,"mongodb, rest apis, fastapi, web scraping"
2,karan.bhatia32@mailtest.example.org,Karan Bhatia,403/hr,Noida,active,"sql, mongodb, selenium, zapier, web scraping, ..."
3,arjun.mishra70@example.com,Arjun Mishra,440/hr,Delhi,ACTIVE,"react, docker, javascript"
4,isha.kapoor54@example.com,Isha Kapoor,15k/month,Delhi,active,"fastapi, python, javascript, selenium, react, ..."
5,ISHA.CHOPRA95@MAILTEST.EXAMPLE.ORG,Isha Chopra,1406/hr,Pune,active,"react, javascript, mysql"
6,meera.bhatia52@mailtest.example.org,Meera Bhatia,330/hr,New Delhi,active,"langchain, docker, mysql, python, sql, react"
7,vikram.saxena60@example.com,Vikram Saxena,843/hr,Gurgaon,Active,"selenium, web scraping, react, docker, sql, fa..."
8,rahul.chopra70@example.com,Rahul Chopra,72k/month,Noida,Inactive,"zapier, docker, python"
9,tanvi.gupta31@example.com,Tanvi Gupta,1331/hr,bangalore,paused,"n8n, langchain, rest apis, mongodb, sql"
12,sneha.chopra99@example.in,Sneha Chopra,28k/month,pune,Active,"pandas, react, mysql, javascript, sql"
13,DEEPAK.NAIR44@EXAMPLE.COM,Deepak Nair,465/hr,Bengaluru,paused,"react, n8n, mongodb, pandas"
14,gaurav.mehta79@mailtest.example.org,Gaurav Mehta,56k/month,bangalore,ACTIVE,"rest apis, sql, selenium, fastapi"
15,NEHA.BHATIA60@MAILTEST.EXAMPLE.ORG,Neha Bhatia,79k/month,PUNE,Active,"fastapi, zapier, javascript, selenium"
16,arjun.mehta77@mailtest.example.org,Arjun Mehta,42k/month,Noida,Inactive,"fastapi, pandas, web scraping, zapier, docker,..."
17,manish.bhatia3@example.com,Manish Bhatia,73k/month,Noida,ACTIVE,"pandas, docker, javascript, react, rest apis, ..."
19,divya.chopra59@example.in,Divya Chopra,55k/month,Noida,Inactive,"zapier, docker, mongodb, fastapi"
24,TANVI.REDDY80@EXAMPLE.COM,Tanvi Reddy,59k/month,pune,paused,"langchain, docker, python, rest apis, sql"
25,varun.singh81@example.com,Varun Singh,763/hr,Noida,ACTIVE,"python, react, fastapi, mongodb"
26,tanvi.kapoor38@example.com,Tanvi Kapoor,38k/month,new delhi,ACTIVE,"docker, selenium, web scraping, mysql"
27,nikhil.nair26@example.in,Nikhil Nair,1018/hr,gurugram,Active,"python, n8n, web scraping"
28,pooja.reddy96@mailtest.example.org,Pooja Reddy,590/hr,Noida,Inactive,"pandas, docker, fastapi, web scraping, sql"
29,TANVI.SHARMA56@MAILTEST.EXAMPLE.ORG,Tanvi Sharma,73k/month,NOIDA,ACTIVE,"langchain, python, web scraping, n8n, fastapi"
30,DEEPAK.NAIR57@EXAMPLE.IN,Deepak Nair,1462/hr,New Delhi,Active,"javascript, react, docker, web scraping, mysql..."
31,anjali.agarwal53@mailtest.example.org,Anjali Agarwal,71k/month,Bengaluru,Inactive,"sql, javascript, selenium, rest apis, docker, ..."

In [88]:
gig_workers_df["email_id"]=gig_workers_df["email_id"].str.lower()
gig_workers_df[["location","status"]]=(gig_workers_df[["location","status"]].apply(lambda col:col.str.strip().str.capitalize()))
gig_workers_df

,email_id,worker_name,rate,location,status,skill_tags
0,varun.jain29@example.com,Varun Jain,1415/hr,Pune,Active,"n8n, web scraping, fastapi, mysql, pandas, mon..."
1,tanvi.agarwal97@example.in,Tanvi Agarwal,1231/hr,Pune,Active,"mongodb, rest apis, fastapi, web scraping"
2,karan.bhatia32@mailtest.example.org,Karan Bhatia,403/hr,Noida,Active,"sql, mongodb, selenium, zapier, web scraping, ..."
3,arjun.mishra70@example.com,Arjun Mishra,440/hr,Delhi,Active,"react, docker, javascript"
4,isha.kapoor54@example.com,Isha Kapoor,15k/month,Delhi,Active,"fastapi, python, javascript, selenium, react, ..."
5,isha.chopra95@mailtest.example.org,Isha Chopra,1406/hr,Pune,Active,"react, javascript, mysql"
6,meera.bhatia52@mailtest.example.org,Meera Bhatia,330/hr,New delhi,Active,"langchain, docker, mysql, python, sql, react"
7,vikram.saxena60@example.com,Vikram Saxena,843/hr,Gurgaon,Active,"selenium, web scraping, react, docker, sql, fa..."
8,rahul.chopra70@example.com,Rahul Chopra,72k/month,Noida,Inactive,"zapier, docker, python"
9,tanvi.gupta31@example.com,Tanvi Gupta,1331/hr,Bangalore,Paused,"n8n, langchain, rest apis, mongodb, sql"
12,sneha.chopra99@example.in,Sneha Chopra,28k/month,Pune,Active,"pandas, react, mysql, javascript, sql"
13,deepak.nair44@example.com,Deepak Nair,465/hr,Bengaluru,Paused,"react, n8n, mongodb, pandas"
14,gaurav.mehta79@mailtest.example.org,Gaurav Mehta,56k/month,Bangalore,Active,"rest apis, sql, selenium, fastapi"
15,neha.bhatia60@mailtest.example.org,Neha Bhatia,79k/month,Pune,Active,"fastapi, zapier, javascript, selenium"
16,arjun.mehta77@mailtest.example.org,Arjun Mehta,42k/month,Noida,Inactive,"fastapi, pandas, web scraping, zapier, docker,..."
17,manish.bhatia3@example.com,Manish Bhatia,73k/month,Noida,Active,"pandas, docker, javascript, react, rest apis, ..."
19,divya.chopra59@example.in,Divya Chopra,55k/month,Noida,Inactive,"zapier, docker, mongodb, fastapi"
24,tanvi.reddy80@example.com,Tanvi Reddy,59k/month,Pune,Paused,"langchain, docker, python, rest apis, sql"
25,varun.singh81@example.com,Varun Singh,763/hr,Noida,Active,"python, react, fastapi, mongodb"
26,tanvi.kapoor38@example.com,Tanvi Kapoor,38k/month,New delhi,Active,"docker, selenium, web scraping, mysql"
27,nikhil.nair26@example.in,Nikhil Nair,1018/hr,Gurugram,Active,"python, n8n, web scraping"
28,pooja.reddy96@mailtest.example.org,Pooja Reddy,590/hr,Noida,Inactive,"pandas, docker, fastapi, web scraping, sql"
29,tanvi.sharma56@mailtest.example.org,Tanvi Sharma,73k/month,Noida,Active,"langchain, python, web scraping, n8n, fastapi"
30,deepak.nair57@example.in,Deepak Nair,1462/hr,New delhi,Active,"javascript, react, docker, web scraping, mysql..."
31,anjali.agarwal53@mailtest.example.org,Anjali Agarwal,71k/month,Bengaluru,Inactive,"sql, javascript, selenium, rest apis, docker, ..."

In [94]:
naukri_clean = naukri_df.rename(columns={
    "Full Name": "name",
    "Email": "email",
    "Phone": "phone",
    "City": "city",
    "Skills": "skills"
})

gig_clean = gig_workers_df.rename(columns={
    "worker_name": "name",
    "email_id": "email",
    "phone": "phone",
    "location": "city",
    "skill_tags": "skills"
})

cbnexus_clean = cbnexus_contacts_df.rename(columns={
    "Name": "name",
    "Email": "email",
    "Phone Number": "phone",
    "City": "city"
})
naukri_clean["source"] = "naukri"
gig_clean["source"] = "gig_workers"
cbnexus_clean["source"] = "cbnexus"

In [95]:
combined_df = pd.concat(
    [naukri_clean, gig_clean, cbnexus_clean],
    ignore_index=True,
    sort=False
)

In [97]:
print(combined_df.shape)
print(combined_df.head())
print(combined_df.columns.tolist())

(97, 13)
            name                               email       phone       city  \
0    Tanvi Gupta           tanvi.gupta31@example.com  9000000254  Bengaluru
1   Manish Reddy          manish.reddy73@example.com  9000000237    Gurgaon
2    Priya Singh  priya.singh61@mailtest.example.org  9000000287    Gurgaon
3  Vikram Saxena         vikram.saxena60@example.com  9000000113    Gurgaon
4   Amit Agarwal  amit.agarwal3@mailtest.example.org  9000000288       Pune

   Experience (Years)  Current CTC Applied Date  \
0                 4.2     417964.0   2026-07-24
1                 3.5     332456.0   2026-08-08
2                 3.0     775670.0   2026-08-01
3                 1.9     654699.0   2026-07-07
4                 1.8          4.2   2026-07-19

                                              skills  source rate status  \
0            n8n, LangChain, REST APIs, MongoDB, SQL  naukri  NaN    NaN
1                         Docker, Zapier, JavaScript  naukri  NaN    NaN
2             React, Zapier, n8n, MySQL, Python, SQL  naukri  NaN    NaN
3  Selenium, Web Scraping, React, Docker, SQL, Fa...  naukri  NaN    NaN
4                    SQL, Python, JavaScript, Docker  naukri  NaN    NaN

  Verified Projects Completed
0      NaN                NaN
1      NaN                NaN
2      NaN                NaN
3      NaN                NaN
4      NaN                NaN
['name', 'email', 'phone', 'city', 'Experience (Years)', 'Current CTC', 'Applied Date', 'skills', 'source', 'rate', 'status', 'Verified', 'Projects Completed']

In [98]:
combined_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97 entries, 0 to 96
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   name                97 non-null     object
 1   email               67 non-null     object
 2   phone               72 non-null     object
 3   city                97 non-null     object
 4   Experience (Years)  42 non-null     float64
 5   Current CTC         42 non-null     float64
 6   Applied Date        42 non-null     object
 7   skills              67 non-null     object
 8   source              97 non-null     object
 9   rate                25 non-null     object
 10  status              25 non-null     object
 11  Verified            30 non-null     object
 12  Projects Completed  30 non-null     object
dtypes: float64(2), object(11)
memory usage: 10.0+ KB

In [99]:
combined_df["name_key"] = (
    combined_df["name"]
    .astype("string")
    .str.strip()
    .str.lower()
)
combined_df["email_key"] = (
    combined_df["email"]
    .astype("string")
    .str.strip()
    .str.lower()
)


combined_df["phone_key"] = (
    combined_df["phone"]
    .astype("string")
    .str.strip()
)
combined_df[
    ["name", "email", "phone", "source",
     "name_key", "email_key", "phone_key"]
].head(10)

,name,email,phone,source,name_key,email_key,phone_key
0,Tanvi Gupta,tanvi.gupta31@example.com,9000000254,naukri,tanvi gupta,tanvi.gupta31@example.com,9000000254
1,Manish Reddy,manish.reddy73@example.com,9000000237,naukri,manish reddy,manish.reddy73@example.com,9000000237
2,Priya Singh,priya.singh61@mailtest.example.org,9000000287,naukri,priya singh,priya.singh61@mailtest.example.org,9000000287
3,Vikram Saxena,vikram.saxena60@example.com,9000000113,naukri,vikram saxena,vikram.saxena60@example.com,9000000113
4,Amit Agarwal,amit.agarwal3@mailtest.example.org,9000000288,naukri,amit agarwal,amit.agarwal3@mailtest.example.org,9000000288
5,Sahil Malhotra,sahil.malhotra1@example.in,9000000143,naukri,sahil malhotra,sahil.malhotra1@example.in,9000000143
6,Shreya Gupta,shreya.gupta85@example.com,9000000227,naukri,shreya gupta,shreya.gupta85@example.com,9000000227
7,Isha Chopra,isha.chopra95@mailtest.example.org,9000000138,naukri,isha chopra,isha.chopra95@mailtest.example.org,9000000138
8,Priya Nair,priya.nair70@example.com,9000000222,naukri,priya nair,priya.nair70@example.com,9000000222
9,Rohit Mishra,rohit.mishra70@mailtest.example.org,9000000167,naukri,rohit mishra,rohit.mishra70@mailtest.example.org,9000000167

In [100]:
email_duplicates = combined_df[
    combined_df["email_key"].duplicated(keep=False)
].sort_values("email_key")

print(email_duplicates[
    ["name", "email", "phone", "source"]
])

              name                                email       phone  \
15    Arjun Mishra           arjun.mishra70@example.com  9000000106
45    Arjun Mishra           arjun.mishra70@example.com         NaN
53     Deepak Nair            deepak.nair44@example.com         NaN
31     Deepak Nair            deepak.nair44@example.com  9000000296
28    Gaurav Mehta  gaurav.mehta79@mailtest.example.org  9000000133
54    Gaurav Mehta  gaurav.mehta79@mailtest.example.org         NaN
7      Isha Chopra   isha.chopra95@mailtest.example.org  9000000138
47     Isha Chopra   isha.chopra95@mailtest.example.org         NaN
38     Isha Kapoor            isha.kapoor54@example.com  9000000295
46     Isha Kapoor            isha.kapoor54@example.com         NaN
13    Karan Bhatia  karan.bhatia32@mailtest.example.org  9000000211
44    Karan Bhatia  karan.bhatia32@mailtest.example.org         NaN
16    Meera Bhatia  meera.bhatia52@mailtest.example.org  9000000223
48    Meera Bhatia  meera.bhatia52@mailtest.example.org         NaN
41     Neha Bhatia   neha.bhatia60@mailtest.example.org  9000000273
55     Neha Bhatia   neha.bhatia60@mailtest.example.org         NaN
32    Rahul Chopra           rahul.chopra70@example.com  9000000137
50    Rahul Chopra           rahul.chopra70@example.com         NaN
29     Rohit Verma   rohit.verma13@mailtest.example.org  9000000294
23        R. Verma   rohit.verma13@mailtest.example.org  9000000294
20    Sneha Chopra            sneha.chopra99@example.in  9000000162
52    Sneha Chopra            sneha.chopra99@example.in         NaN
43   Tanvi Agarwal           tanvi.agarwal97@example.in         NaN
36   Tanvi Agarwal           tanvi.agarwal97@example.in  9000000148
51     Tanvi Gupta            tanvi.gupta31@example.com         NaN
0      Tanvi Gupta            tanvi.gupta31@example.com  9000000254
42      Varun Jain             varun.jain29@example.com         NaN
17      Varun Jain             varun.jain29@example.com  9000000263
49   Vikram Saxena          vikram.saxena60@example.com         NaN
3    Vikram Saxena          vikram.saxena60@example.com  9000000113
67      Rohit Nair                                  NaN  9000000268
68     Ritu Sharma                                  NaN  9000000146
69    Priya Saxena                                  NaN  9000000231
70     Arjun Mehta                                  NaN  9000000131
71    Nikhil Mehta                                  NaN  9000000104
72  Rahul Malhotra                                  NaN  9000000260
73    Deepak Mehta                                  NaN  9000000116
74  Sahil Malhotra                                  NaN  9000000143
75    Shreya Gupta                                  NaN  9000000227
76     Priya Singh                                  NaN  9000000287
77      Varun Jain                                  NaN  9000000263
78   Tanvi Agarwal                                  NaN  9000000148
79    Karan Bhatia                                  NaN  9000000211
80    Arjun Mishra                                  NaN  9000000106
81     Isha Kapoor                                  NaN  9000000295
82     Isha Chopra                                  NaN  9000000138
83    Meera Bhatia                                  NaN  9000000223
84   Vikram Saxena                                  NaN  9000000113
85    Rahul Chopra                                  NaN  9000000137
86     Tanvi Gupta                                  NaN  9000000254
87    Varun Saxena                                  NaN  9000000170
88    Sneha Chopra                                  NaN  9000000162
89     Deepak Nair                                  NaN  9000000296
90    Gaurav Mehta                                  NaN  9000000133
91     Neha Bhatia                                  NaN  9000000273
92     Arjun Mehta                                  NaN  9000000272
93   Manish Bhatia                                  NaN  9000000161
94    Divya Chopra                                  NaN  9000000111
95    Karan Chopra                                  NaN  9000000245
96    Vikram Mehta                                  NaN  9000000261

         source
15       naukri
45  gig_workers
53  gig_workers
31       naukri
28       naukri
54  gig_workers
7        naukri
47  gig_workers
38       naukri
46  gig_workers
13       naukri
44  gig_workers
16       naukri
48  gig_workers
41       naukri
55  gig_workers
32       naukri
50  gig_workers
29       naukri
23       naukri
20       naukri
52  gig_workers
43  gig_workers
36       naukri
51  gig_workers
0        naukri
42  gig_workers
17       naukri
49  gig_workers
3        naukri
67      cbnexus
68      cbnexus
69      cbnexus
70      cbnexus
71      cbnexus
72      cbnexus
73      cbnexus
74      cbnexus
75      cbnexus
76      cbnexus
77      cbnexus
78      cbnexus
79      cbnexus
80      cbnexus
81      cbnexus
82      cbnexus
83      cbnexus
84      cbnexus
85      cbnexus
86      cbnexus
87      cbnexus
88      cbnexus
89      cbnexus
90      cbnexus
91      cbnexus
92      cbnexus
93      cbnexus
94      cbnexus
95      cbnexus
96      cbnexus

In [101]:
phone_duplicates = combined_df[
    combined_df["phone_key"].notna()
    & combined_df["phone_key"].duplicated(keep=False)
].sort_values("phone_key")

print(
    phone_duplicates[
        ["name", "email", "phone", "city", "source"]
    ].to_string(index=False)
)

          name                                 email      phone      city  source
 Nikhil Chopra           nikhil.chopra70@example.com 9000000103     Noida  naukri
 Nikhil Chopra       alt.nikhil.chopra70@example.com 9000000103     Noida  naukri
  Nikhil Mehta             nikhil.mehta5@example.com 9000000104      Pune  naukri
  Nikhil Mehta                                   NaN 9000000104      Pune cbnexus
  Arjun Mishra                                   NaN 9000000106 New Delhi cbnexus
  Arjun Mishra            arjun.mishra70@example.com 9000000106     Delhi  naukri
 Vikram Saxena           vikram.saxena60@example.com 9000000113   Gurgaon  naukri
 Vikram Saxena                                   NaN 9000000113   Gurgaon cbnexus
  Deepak Mehta             deepak.mehta86@example.in 9000000116     Noida  naukri
  Deepak Mehta                                   NaN 9000000116     Noida cbnexus
   Arjun Mehta               arjun.mehta9@example.in 9000000131     Noida  naukri
   Arjun Mehta                                   NaN 9000000131     Noida cbnexus
  Gaurav Mehta   gaurav.mehta79@mailtest.example.org 9000000133 Bengaluru  naukri
  Gaurav Mehta                                   NaN 9000000133 Bengaluru cbnexus
  Rahul Chopra                                   NaN 9000000137    Noida  cbnexus
  Rahul Chopra            rahul.chopra70@example.com 9000000137     Noida  naukri
   Isha Chopra                                   NaN 9000000138      Pune cbnexus
   Isha Chopra    isha.chopra95@mailtest.example.org 9000000138      Pune  naukri
Sahil Malhotra                                   NaN 9000000143     Noida cbnexus
Sahil Malhotra            sahil.malhotra1@example.in 9000000143     Noida  naukri
   Ritu Sharma                                   NaN 9000000146    Noida  cbnexus
   Ritu Sharma    ritu.sharma23@mailtest.example.org 9000000146    Noida   naukri
 Tanvi Agarwal                                   NaN 9000000148      Pune cbnexus
 Tanvi Agarwal            tanvi.agarwal97@example.in 9000000148      Pune  naukri
  Sneha Chopra             sneha.chopra99@example.in 9000000162      Pune  naukri
  Sneha Chopra                                   NaN 9000000162      Pune cbnexus
  Varun Saxena             varun.saxena21@example.in 9000000170 Gurugram   naukri
  Varun Saxena                                   NaN 9000000170   Gurgaon cbnexus
  Karan Bhatia                                   NaN 9000000211     Noida cbnexus
  Karan Bhatia   karan.bhatia32@mailtest.example.org 9000000211    Noida   naukri
  Meera Bhatia   meera.bhatia52@mailtest.example.org 9000000223 Delhi Ncr  naukri
  Meera Bhatia                                   NaN 9000000223     Delhi cbnexus
  Shreya Gupta                                   NaN 9000000227     Noida cbnexus
  Shreya Gupta            shreya.gupta85@example.com 9000000227     Noida  naukri
  Priya Saxena            priya.saxena61@example.com 9000000231     Delhi  naukri
  Priya Saxena                                   NaN 9000000231 New Delhi cbnexus
   Tanvi Gupta                                   NaN 9000000254 Bengaluru cbnexus
   Tanvi Gupta             tanvi.gupta31@example.com 9000000254 Bengaluru  naukri
Rahul Malhotra rahul.malhotra69@mailtest.example.org 9000000260 New Delhi  naukri
Rahul Malhotra                                   NaN 9000000260 Delhi Ncr cbnexus
    Varun Jain                                   NaN 9000000263      Pune cbnexus
    Varun Jain              varun.jain29@example.com 9000000263      Pune  naukri
    Rohit Nair                                   NaN 9000000268   Gurgaon cbnexus
    Rohit Nair     rohit.nair32@mailtest.example.org 9000000268  Gurugram  naukri
   Neha Bhatia    neha.bhatia60@mailtest.example.org 9000000273      Pune  naukri
   Neha Bhatia                                   NaN 9000000273      Pune cbnexus
   Priya Singh                                   NaN 9000000287 Gurugram  cbnexus
   Priya Singh    priya.singh61@mailtest.example.org 9000000287   Gurgaon  naukri
   Rohit Verma    rohit.verma13@mailtest.example.org 9000000294 Bangalore  naukri
      R. Verma    rohit.verma13@mailtest.example.org 9000000294 Bangalore  naukri
   Isha Kapoor             isha.kapoor54@example.com 9000000295 New Delhi  naukri
   Isha Kapoor                                   NaN 9000000295 New Delhi cbnexus
   Deepak Nair             deepak.nair44@example.com 9000000296 Bangalore  naukri
   Deepak Nair                                   NaN 9000000296 Bengaluru cbnexus

In [106]:
matching_df = combined_df.copy()
email_to_person = {}
phone_to_person = {}

person_counter = 1

person_ids = []

for _, row in matching_df.iterrows():

    email = row["email_key"]
    phone = row["phone_key"]
    name = row["name_key"]

    person_id = None

    # 1. Try email match
    if pd.notna(email) and email in email_to_person:
        person_id = email_to_person[email]

    # 2. If no email match, try phone
    elif pd.notna(phone) and phone in phone_to_person:
        person_id = phone_to_person[phone]

    # 3. No existing match → create new person
    else:
        person_id = f"P{person_counter:04d}"
        person_counter += 1

    # Store the assigned person ID
    person_ids.append(person_id)

    # Update mappings
    if pd.notna(email):
        email_to_person[email] = person_id

    if pd.notna(phone):
        phone_to_person[phone] = person_id


matching_df["person_id"] = person_ids
matching_df

,name,email,phone,city,Experience (Years),Current CTC,Applied Date,skills,source,rate,status,Verified,Projects Completed,name_key,email_key,phone_key,person_id
0,Tanvi Gupta,tanvi.gupta31@example.com,9000000254,Bengaluru,4.2,417964.0,2026-07-24,"n8n, LangChain, REST APIs, MongoDB, SQL",naukri,NaN,NaN,NaN,NaN,tanvi gupta,tanvi.gupta31@example.com,9000000254,P0001
1,Manish Reddy,manish.reddy73@example.com,9000000237,Gurgaon,3.5,332456.0,2026-08-08,"Docker, Zapier, JavaScript",naukri,NaN,NaN,NaN,NaN,manish reddy,manish.reddy73@example.com,9000000237,P0002
2,Priya Singh,priya.singh61@mailtest.example.org,9000000287,Gurgaon,3.0,775670.0,2026-08-01,"React, Zapier, n8n, MySQL, Python, SQL",naukri,NaN,NaN,NaN,NaN,priya singh,priya.singh61@mailtest.example.org,9000000287,P0003
3,Vikram Saxena,vikram.saxena60@example.com,9000000113,Gurgaon,1.9,654699.0,2026-07-07,"Selenium, Web Scraping, React, Docker, SQL, Fa...",naukri,NaN,NaN,NaN,NaN,vikram saxena,vikram.saxena60@example.com,9000000113,P0004
4,Amit Agarwal,amit.agarwal3@mailtest.example.org,9000000288,Pune,1.8,4.2,2026-07-19,"SQL, Python, JavaScript, Docker",naukri,NaN,NaN,NaN,NaN,amit agarwal,amit.agarwal3@mailtest.example.org,9000000288,P0005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,Arjun Mehta,NaN,9000000272,Noida,NaN,NaN,NaN,NaN,cbnexus,NaN,NaN,Y,14,arjun mehta,<NA>,9000000272,P0052
93,Manish Bhatia,NaN,9000000161,Noida,NaN,NaN,NaN,NaN,cbnexus,NaN,NaN,Y,5,manish bhatia,<NA>,9000000161,P0053
94,Divya Chopra,NaN,9000000111,Noida,NaN,NaN,NaN,NaN,cbnexus,NaN,NaN,N,5,divya chopra,<NA>,9000000111,P0054
95,Karan Chopra,NaN,9000000245,Pune,NaN,NaN,NaN,NaN,cbnexus,NaN,NaN,N,10,karan chopra,<NA>,9000000245,P0055
96,Vikram Mehta,NaN,9000000261,Pune,NaN,NaN,NaN,NaN,cbnexus,NaN,NaN,Y,2,vikram mehta,<NA>,9000000261,P0056

In [107]:
print(matching_df[
    ["person_id", "name", "email", "phone", "source"]
].sort_values("person_id").to_string(index=False))

person_id            name                                 email      phone      source
    P0001     Tanvi Gupta             tanvi.gupta31@example.com 9000000254      naukri
    P0001     Tanvi Gupta                                   NaN 9000000254     cbnexus
    P0001     Tanvi Gupta             tanvi.gupta31@example.com        NaN gig_workers
    P0002    Manish Reddy            manish.reddy73@example.com 9000000237      naukri
    P0003     Priya Singh                                   NaN 9000000287     cbnexus
    P0003     Priya Singh    priya.singh61@mailtest.example.org 9000000287      naukri
    P0004   Vikram Saxena                                   NaN 9000000113     cbnexus
    P0004   Vikram Saxena           vikram.saxena60@example.com 9000000113      naukri
    P0004   Vikram Saxena           vikram.saxena60@example.com        NaN gig_workers
    P0005    Amit Agarwal    amit.agarwal3@mailtest.example.org 9000000288      naukri
    P0006  Sahil Malhotra            sahil.malhotra1@example.in 9000000143      naukri
    P0006  Sahil Malhotra                                   NaN 9000000143     cbnexus
    P0007    Shreya Gupta            shreya.gupta85@example.com 9000000227      naukri
    P0007    Shreya Gupta                                   NaN 9000000227     cbnexus
    P0008     Isha Chopra                                   NaN 9000000138     cbnexus
    P0008     Isha Chopra    isha.chopra95@mailtest.example.org        NaN gig_workers
    P0008     Isha Chopra    isha.chopra95@mailtest.example.org 9000000138      naukri
    P0009      Priya Nair              priya.nair70@example.com 9000000222      naukri
    P0010    Rohit Mishra   rohit.mishra70@mailtest.example.org 9000000167      naukri
    P0011  Rahul Malhotra rahul.malhotra69@mailtest.example.org 9000000260      naukri
    P0011  Rahul Malhotra                                   NaN 9000000260     cbnexus
    P0012      Rahul Jain               rahul.jain34@example.in 9000000114      naukri
    P0013 Nikhil Malhotra          nikhil.malhotra41@example.in 9000000145      naukri
    P0014    Karan Bhatia   karan.bhatia32@mailtest.example.org        NaN gig_workers
    P0014    Karan Bhatia   karan.bhatia32@mailtest.example.org 9000000211      naukri
    P0014    Karan Bhatia                                   NaN 9000000211     cbnexus
    P0015     Ritu Sharma                                   NaN 9000000146     cbnexus
    P0015     Ritu Sharma    ritu.sharma23@mailtest.example.org 9000000146      naukri
    P0016    Arjun Mishra                                   NaN 9000000106     cbnexus
    P0016    Arjun Mishra            arjun.mishra70@example.com        NaN gig_workers
    P0016    Arjun Mishra            arjun.mishra70@example.com 9000000106      naukri
    P0017    Meera Bhatia                                   NaN 9000000223     cbnexus
    P0017    Meera Bhatia   meera.bhatia52@mailtest.example.org        NaN gig_workers
    P0017    Meera Bhatia   meera.bhatia52@mailtest.example.org 9000000223      naukri
    P0018      Varun Jain                                   NaN 9000000263     cbnexus
    P0018      Varun Jain              varun.jain29@example.com 9000000263      naukri
    P0018      Varun Jain              varun.jain29@example.com        NaN gig_workers
    P0019     Arjun Mehta                                   NaN 9000000131     cbnexus
    P0019     Arjun Mehta               arjun.mehta9@example.in 9000000131      naukri
    P0020     Kavya Mehta              kavya.mehta7@example.com 9000000177      naukri
    P0021    Sneha Chopra             sneha.chopra99@example.in        NaN gig_workers
    P0021    Sneha Chopra                                   NaN 9000000162     cbnexus
    P0021    Sneha Chopra             sneha.chopra99@example.in 9000000162      naukri
    P0022    Deepak Mehta                                   NaN 9000000116     cbnexus
    P0022    Deepak Mehta             deepak.mehta86@example.in 9000000116      naukri
    P0023     Pooja Gupta    pooja.gupta57@mailtest.example.org 9000000271      naukri
    P0024     Rohit Verma    rohit.verma13@mailtest.example.org 9000000294      naukri
    P0024        R. Verma    rohit.verma13@mailtest.example.org 9000000294      naukri
    P0025    Sneha Mishra   sneha.mishra14@mailtest.example.org 9000000229      naukri
    P0026   Nikhil Chopra       alt.nikhil.chopra70@example.com 9000000103      naukri
    P0026   Nikhil Chopra           nikhil.chopra70@example.com 9000000103      naukri
    P0027    Priya Saxena                                   NaN 9000000231     cbnexus
    P0027    Priya Saxena            priya.saxena61@example.com 9000000231      naukri
    P0028    Varun Saxena                                   NaN 9000000170     cbnexus
    P0028    Varun Saxena             varun.saxena21@example.in 9000000170      naukri
    P0029    Gaurav Mehta   gaurav.mehta79@mailtest.example.org 9000000133      naukri
    P0029    Gaurav Mehta   gaurav.mehta79@mailtest.example.org        NaN gig_workers
    P0029    Gaurav Mehta                                   NaN 9000000133     cbnexus
    P0030      Rohit Nair     rohit.nair32@mailtest.example.org 9000000268      naukri
    P0030      Rohit Nair                                   NaN 9000000268     cbnexus
    P0031     Deepak Nair             deepak.nair44@example.com        NaN gig_workers
    P0031     Deepak Nair             deepak.nair44@example.com 9000000296      naukri
    P0031     Deepak Nair                                   NaN 9000000296     cbnexus
    P0032    Rahul Chopra            rahul.chopra70@example.com        NaN gig_workers
    P0032    Rahul Chopra            rahul.chopra70@example.com 9000000137      naukri
    P0032    Rahul Chopra                                   NaN 9000000137     cbnexus
    P0033    Deepak Singh   deepak.singh36@mailtest.example.org 9000000202      naukri
    P0034      Amit Reddy      amit.reddy9@mailtest.example.org 9000000165      naukri
    P0035   Tanvi Agarwal            tanvi.agarwal97@example.in        NaN gig_workers
    P0035   Tanvi Agarwal                                   NaN 9000000148     cbnexus
    P0035   Tanvi Agarwal            tanvi.agarwal97@example.in 9000000148      naukri
    P0036    Nikhil Mehta             nikhil.mehta5@example.com 9000000104      naukri
    P0036    Nikhil Mehta                                   NaN 9000000104     cbnexus
    P0037     Isha Kapoor             isha.kapoor54@example.com 9000000295      naukri
    P0037     Isha Kapoor             isha.kapoor54@example.com        NaN gig_workers
    P0037     Isha Kapoor                                   NaN 9000000295     cbnexus
    P0038    Arjun Bhatia            arjun.bhatia14@example.com 9000000212      naukri
    P0039     Isha Sharma             isha.sharma15@example.com 9000000259      naukri
    P0040     Neha Bhatia    neha.bhatia60@mailtest.example.org        NaN gig_workers
    P0040     Neha Bhatia    neha.bhatia60@mailtest.example.org 9000000273      naukri
    P0040     Neha Bhatia                                   NaN 9000000273     cbnexus
    P0041     Arjun Mehta    arjun.mehta77@mailtest.example.org        NaN gig_workers
    P0042   Manish Bhatia            manish.bhatia3@example.com        NaN gig_workers
    P0043    Divya Chopra             divya.chopra59@example.in        NaN gig_workers
    P0044     Tanvi Reddy             tanvi.reddy80@example.com        NaN gig_workers
    P0045     Varun Singh             varun.singh81@example.com        NaN gig_workers
    P0046    Tanvi Kapoor            tanvi.kapoor38@example.com        NaN gig_workers
    P0047     Nikhil Nair              nikhil.nair26@example.in        NaN gig_workers
    P0048     Pooja Reddy    pooja.reddy96@mailtest.example.org        NaN gig_workers
    P0049    Tanvi Sharma   tanvi.sharma56@mailtest.example.org        NaN gig_workers
    P0050     Deepak Nair              deepak.nair57@example.in        NaN gig_workers
    P0051  Anjali Agarwal anjali.agarwal53@mailtest.example.org        NaN gig_workers
    P0052     Arjun Mehta                                   NaN 9000000272     cbnexus
    P0053   Manish Bhatia                                   NaN 9000000161     cbnexus
    P0054    Divya Chopra                                   NaN 9000000111     cbnexus
    P0055    Karan Chopra                                   NaN 9000000245     cbnexus
    P0056    Vikram Mehta                                   NaN 9000000261     cbnexus

In [108]:
print("Total source records:", len(matching_df))
print("Unique people:", matching_df["person_id"].nunique())
print("Records merged:", len(matching_df) - matching_df["person_id"].nunique())

Total source records: 97
Unique people: 56
Records merged: 41

In [122]:
def first_valid(series):
    values = series.dropna()
    
    if len(values) == 0:
        return pd.NA
    
    return values.iloc[0]

def combine_skills(series):
    skills = set()

    for value in series.dropna():
        for skill in str(value).split(","):
            skill = skill.strip()

            if skill:
                skills.add(skill)

    return ", ".join(sorted(skills))


def combine_emails(series):
    emails = set()

    for value in series.dropna():
        value = str(value).strip().lower()

        if value:
            emails.add(value)

    return ", ".join(sorted(emails))

In [123]:
master_people = (
    matching_df
    .groupby("person_id")
    .agg(
        name=("name", first_valid),
        email=("email", combine_emails),
        phone=("phone", first_valid),
        city=("city", first_valid),
        skills=("skills", combine_skills),
        sources=("source", lambda x: ", ".join(sorted(set(x))))
    )
    .reset_index()
)

In [111]:
print(master_people.shape)

(56, 7)

In [124]:
master_people.head(10)

,person_id,name,email,phone,city,skills,sources
0,P0001,Tanvi Gupta,tanvi.gupta31@example.com,9000000254,Bengaluru,"LangChain, MongoDB, REST APIs, SQL, langchain,...","cbnexus, gig_workers, naukri"
1,P0002,Manish Reddy,manish.reddy73@example.com,9000000237,Gurgaon,"Docker, JavaScript, Zapier",naukri
2,P0003,Priya Singh,priya.singh61@mailtest.example.org,9000000287,Gurgaon,"MySQL, Python, React, SQL, Zapier, n8n","cbnexus, naukri"
3,P0004,Vikram Saxena,vikram.saxena60@example.com,9000000113,Gurgaon,"Docker, FastAPI, React, SQL, Selenium, Web Scr...","cbnexus, gig_workers, naukri"
4,P0005,Amit Agarwal,amit.agarwal3@mailtest.example.org,9000000288,Pune,"Docker, JavaScript, Python, SQL",naukri
5,P0006,Sahil Malhotra,sahil.malhotra1@example.in,9000000143,Noida,"Docker, FastAPI, MySQL, Pandas, REST APIs, Zapier","cbnexus, naukri"
6,P0007,Shreya Gupta,shreya.gupta85@example.com,9000000227,Noida,"Docker, Python, Web Scraping, Zapier, n8n","cbnexus, naukri"
7,P0008,Isha Chopra,isha.chopra95@mailtest.example.org,9000000138,Pune,"JavaScript, MySQL, React, javascript, mysql, r...","cbnexus, gig_workers, naukri"
8,P0009,Priya Nair,priya.nair70@example.com,9000000222,Gurugram,"Python, REST APIs, React, Web Scraping, Zapier...",naukri
9,P0010,Rohit Mishra,rohit.mishra70@mailtest.example.org,9000000167,Delhi,"Docker, FastAPI, MySQL, Pandas, SQL, Zapier",naukri

In [125]:
print("Total people:", len(master_people))
print("Missing names:", master_people["name"].isna().sum())
print("Missing emails:", master_people["email"].isna().sum())
print("Missing phones:", master_people["phone"].isna().sum())

Total people: 56
Missing names: 0
Missing emails: 0
Missing phones: 11

In [128]:
naukri_records = matching_df[
    matching_df["source"] == "naukri"
][[
    "person_id",
    "name",
    "email",
    "phone",
    "city",
    "Experience (Years)",
    "Current CTC",
    "Applied Date",
    "skills"
]].copy()

gig_records = matching_df[
    matching_df["source"] == "gig_workers"
][[
    "person_id",
    "name",
    "email",
    "phone",
    "city",
    "rate",
    "status",
    "skills"
]].copy()

cbnexus_records = matching_df[
    matching_df["source"] == "cbnexus"
][[
    "person_id",
    "name",
    "phone",
    "city",
    "Verified",
    "Projects Completed"
]].copy()

In [129]:
naukri_records["source_record_id"] = [
    f"NAUKRI_{i+1:04d}"
    for i in range(len(naukri_records))
]

gig_records["source_record_id"] = [
    f"GIG_{i+1:04d}"
    for i in range(len(gig_records))
]

cbnexus_records["source_record_id"] = [
    f"CBNEXUS_{i+1:04d}"
    for i in range(len(cbnexus_records))
]

In [131]:
person_sources = matching_df[
    ["person_id", "source"]
].copy()

person_sources = person_sources.drop_duplicates().reset_index(drop=True)
person_sources.tail()

   person_id   source
90     P0052  cbnexus
91     P0053  cbnexus
92     P0054  cbnexus
93     P0055  cbnexus
94     P0056  cbnexus

In [134]:
expected_relationships = matching_df[
    ["person_id", "source"]
].drop_duplicates()

print("Expected source relationships:", len(expected_relationships))
print("Our source relationships:", len(person_sources))

Expected source relationships: 95
Our source relationships: 95

In [136]:
import sqlite3

conn = sqlite3.connect("assignment.db")
cursor = conn.cursor()

print("Database connected successfully!")

Database connected successfully!

In [138]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS persons (
    person_id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    city TEXT,
    skills TEXT,
    sources TEXT
)
""")
cursor.execute("""
CREATE TABLE IF NOT EXISTS naukri_records (
    source_record_id TEXT PRIMARY KEY,
    person_id TEXT NOT NULL,
    name TEXT,
    email TEXT,
    phone TEXT,
    city TEXT,
    experience_years REAL,
    current_ctc REAL,
    applied_date TEXT,
    skills TEXT,
    FOREIGN KEY (person_id) REFERENCES persons(person_id)
)
""")
cursor.execute("""
CREATE TABLE IF NOT EXISTS gig_worker_records (
    source_record_id TEXT PRIMARY KEY,
    person_id TEXT NOT NULL,
    name TEXT,
    email TEXT,
    phone TEXT,
    city TEXT,
    rate TEXT,
    status TEXT,
    skills TEXT,
    FOREIGN KEY (person_id) REFERENCES persons(person_id)
)
""")
cursor.execute("""
CREATE TABLE IF NOT EXISTS cbnexus_records (
    source_record_id TEXT PRIMARY KEY,
    person_id TEXT NOT NULL,
    name TEXT,
    phone TEXT,
    city TEXT,
    verified TEXT,
    projects_completed INTEGER,
    FOREIGN KEY (person_id) REFERENCES persons(person_id)
)
""")
cursor.execute("""
CREATE TABLE IF NOT EXISTS person_sources (
    person_id TEXT NOT NULL,
    source TEXT NOT NULL,
    PRIMARY KEY (person_id, source),
    FOREIGN KEY (person_id) REFERENCES persons(person_id)
)
""")

cursor.execute("""
CREATE TABLE IF NOT EXISTS audio_submissions (
    submission_id INTEGER PRIMARY KEY AUTOINCREMENT,
    person_id TEXT,
    file_path TEXT NOT NULL,
    transcript TEXT,
    extracted_fields TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (person_id) REFERENCES persons(person_id)
)
""")

In [141]:
conn.commit()

In [142]:
master_people.to_sql(
    "persons",
    conn,
    if_exists="append",
    index=False
)

56

In [143]:
cursor.execute("SELECT COUNT(*) FROM persons")
print("People:", cursor.fetchone()[0])

People: 56

In [144]:
naukri_sql = naukri_records.rename(columns={
    "Experience (Years)": "experience_years",
    "Current CTC": "current_ctc",
    "Applied Date": "applied_date"
}).copy()

In [145]:
print(naukri_sql.columns.tolist())

['person_id', 'name', 'email', 'phone', 'city', 'experience_years', 'current_ctc', 'applied_date', 'skills', 'source_record_id']

In [146]:
naukri_sql.to_sql(
    "naukri_records",
    conn,
    if_exists="append",
    index=False
)

42

In [147]:
cursor.execute("SELECT COUNT(*) FROM naukri_records")
print("Naukri records:", cursor.fetchone()[0])

Naukri records: 42

In [150]:
gig_records.to_sql(
    "gig_worker_records",
    conn,
    if_exists="append",
    index=False
)

IntegrityError: UNIQUE constraint failed: gig_worker_records.source_record_id

In [151]:
cursor.execute("SELECT COUNT(*) FROM gig_worker_records")
print("Gig records:", cursor.fetchone()[0])

Gig records: 25

OperationalError: table cbnexus_records has no column named Projects Completed

In [156]:
cbnexus_sql.to_sql(
    "cbnexus_records",
    conn,
    if_exists="append",
    index=False
)

IntegrityError: UNIQUE constraint failed: cbnexus_records.source_record_id

In [157]:
cursor.execute("SELECT COUNT(*) FROM cbnexus_records")
print("CBNexus records:", cursor.fetchone()[0])

CBNexus records: 30

In [158]:
tables = [
    "persons",
    "naukri_records",
    "gig_worker_records",
    "cbnexus_records",
    "person_sources",
    "audio_submissions"
]

for table in tables:
    count = pd.read_sql_query(
        f"SELECT COUNT(*) AS count FROM {table}",
        conn
    ).iloc[0]["count"]

    print(f"{table}: {count}")

persons: 56
naukri_records: 42
gig_worker_records: 25
cbnexus_records: 30
person_sources: 0
audio_submissions: 0

In [159]:
person_sources.to_sql(
    "person_sources",
    conn,
    if_exists="append",
    index=False
)

95

In [160]:
cursor.execute("SELECT COUNT(*) FROM person_sources")
print("Source relationships:", cursor.fetchone()[0])

Source relationships: 95

In [161]:
pd.read_sql_query(
    """
    SELECT *
    FROM person_sources
    LIMIT 10
    """,
    conn
)

  person_id  source
0     P0001  naukri
1     P0002  naukri
2     P0003  naukri
3     P0004  naukri
4     P0005  naukri
5     P0006  naukri
6     P0007  naukri
7     P0008  naukri
8     P0009  naukri
9     P0010  naukri

In [162]:
pd.read_sql_query(
    """
    SELECT
        p.person_id,
        p.name,
        ps.source
    FROM persons p
    JOIN person_sources ps
        ON p.person_id = ps.person_id
    WHERE p.person_id = 'P0001'
    """,
    conn
)

  person_id         name       source
0     P0001  Tanvi Gupta      cbnexus
1     P0001  Tanvi Gupta  gig_workers
2     P0001  Tanvi Gupta       naukri

In [163]:
tables = [
    "persons",
    "naukri_records",
    "gig_worker_records",
    "cbnexus_records",
    "person_sources",
    "audio_submissions"
]

for table in tables:
    count = pd.read_sql_query(
        f"SELECT COUNT(*) AS count FROM {table}",
        conn
    ).iloc[0]["count"]

    print(f"{table}: {count}")

persons: 56
naukri_records: 42
gig_worker_records: 25
cbnexus_records: 30
person_sources: 95
audio_submissions: 0

In [165]:
cursor.execute("DROP TABLE audio_submissions")
conn.commit()

In [166]:
cursor.execute("""
CREATE TABLE audio_submissions (
    submission_id INTEGER PRIMARY KEY AUTOINCREMENT,
    person_id TEXT,
    name TEXT NOT NULL,
    phone TEXT NOT NULL,
    file_path TEXT NOT NULL,
    duration_seconds REAL,
    sample_rate_khz REAL,
    bitrate_kbps REAL,
    loudness_db REAL,
    noise_quality TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (person_id)
        REFERENCES persons(person_id)
)
""")

conn.commit()

In [167]:
pd.read_sql_query(
    "PRAGMA table_info(audio_submissions)",
    conn
)

    cid              name     type  notnull         dflt_value  pk
0     0     submission_id  INTEGER        0               None   1
1     1         person_id     TEXT        0               None   0
2     2              name     TEXT        1               None   0
3     3             phone     TEXT        1               None   0
4     4         file_path     TEXT        1               None   0
5     5  duration_seconds     REAL        0               None   0
6     6   sample_rate_khz     REAL        0               None   0
7     7      bitrate_kbps     REAL        0               None   0
8     8       loudness_db     REAL        0               None   0
9     9     noise_quality     TEXT        0               None   0
10   10        created_at     TEXT        0  CURRENT_TIMESTAMP   0

In [168]:
pd.read_sql_query(
    """
    SELECT
        submission_id,
        person_id,
        name,
        phone,
        duration_seconds,
        sample_rate_khz,
        bitrate_kbps,
        loudness_db,
        file_path,
        created_at
    FROM audio_submissions
    ORDER BY submission_id DESC
    """,
    conn
)

,submission_id,person_id,name,phone,duration_seconds,sample_rate_khz,bitrate_kbps,loudness_db,file_path,created_at
0,2,P0001,Tanvi Gupta,9000000254,13.85997,48.0,129.528,-40.5,C:\Users\DELL\Downloads\Consultbae Assignement...,2026-08-15 07:44:26
1,1,P0001,Tanvi Gupta,9000000254,5.00000,44.1,705.600,-21.1,C:\Users\DELL\Downloads\Consultbae Assignement...,2026-08-15 07:39:23